services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - shared-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - shared-network
networks:
  shared-network:
    external: true

# sudo docker run --rm \
#   -v $(pwd)/certbot/www:/var/www/certbot \
#   -v $(pwd)/certbot/conf:/etc/letsencrypt \
#   certbot/certbot certonly \
#   --webroot -w /var/www/certbot \
#   -d jibbles.netrunnerdebugs.party \
#   --agree-tos \
#   --non-interactive \
#   --email shaahid.adams@gmail.com
